# Generated by Django 4.1.7 on 2023-03-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userorder",
            name="amount",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
