# Generated by Django 4.1.7 on 2023-03-09 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shopping_cart", "0002_cart_cartproduct_delete_shoppingcart_cart_products"),
        ("users", "0002_alter_user_updatedat"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cart",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="shopping_cart.cart",
            ),
        ),
    ]
