# Generated by Django 4.1.7 on 2023-03-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
