# Generated by Django 4.1.7 on 2023-03-12 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_product_category"),
        ("users", "0003_user_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="userorder",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("Pedido Realizado", "Order Placed"),
                    ("Em Andamento", "In Progress"),
                    ("Entregue", "Delivered"),
                ],
                default="Pedido Realizado",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="userorder",
            name="ordered_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userorder",
            name="ordered_by",
            field=models.ForeignKey(
                default="29d33f90-a744-41e8-a86f-71e2155122ff",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products_orders",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userorder",
            name="product",
            field=models.ForeignKey(
                default="b46210ce-002f-450c-b5c9-5b6d12c02bb6",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="products.product",
            ),
            preserve_default=False,
        ),
    ]
