# Generated by Django 4.1.7 on 2023-03-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_userorder_order_status_userorder_ordered_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
