# Generated by Django 4.1.7 on 2023-03-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_updatedat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="updatedAt",
            field=models.DateTimeField(null=True),
        ),
    ]
