# Generated by Django 4.1.7 on 2023-03-12 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_rename_category_name_category_category"),
        ("products", "0005_alter_product_category_alter_product_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="categories.category",
            ),
        ),
    ]
